apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "metrics-server-exporter.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "metrics-server-exporter.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "metrics-server-exporter.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}