name: ci
on:
  push:
    branches:
      - "master"
    tags:
      - '*.*.*'
jobs:
  CI:
    runs-on: ubuntu-latest
    name: metrics-server-exporter
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run TruffleHog
        run: |
          docker pull dxa4481/trufflehog
          docker run -v ${{ github.workspace }}:/target dxa4481/trufflehog --entropy=False file:///target
      - name: List files in path
        run: ls -la .
      # - name: 'Qodana Scan'
      #   uses: JetBrains/qodana-action@v2023.3
      #   env:
      #     QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
           name: Depcheck report
           path: ${{github.workspace}}/reports
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/metrics-server-exporter:latest, ${{ secrets.DOCKER_HUB_USERNAME }}/metrics-server-exporter:${{ env.RELEASE_VERSION }}
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKER_HUB_USERNAME }}/metrics-server-exporter:${{ env.RELEASE_VERSION }}
          format: 'table'
          exit-code: '0'
          severity: 'HIGH'
      - name: Run Trivy vulnerability scanner (CRITICAL)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKER_HUB_USERNAME }}/metrics-server-exporter:${{ env.RELEASE_VERSION }}
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL'
#      - name: Staticcheck is a state of the art linter for the Go programming language
#        uses: dominikh/staticcheck-action@v1.3.0
#        with:
#          version: "2023.1.6"
